### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by heyprincesingh** [cynthiakonar/news-app#3]
If you want I can add a custom splash screen (3-5Sec) for main screen which will give a professional look to the application.
Tell me by adding the Hacktoberfest label and i'm good to go.
Thanks!

**Comment by cynthiakonar** [comment]
Sure, go ahead

**Comment by pratikagr** [comment]
assign me

**Comment by cynthiakonar** [comment]
> assign me

hi! this issue is already taken, please go ahead and create an issue to work on a feature
